### ISSUE TITLE
Provide https Repository

### ISSUE THREAD

**Issue by MichaelKunze** [sephiroth-j/spring-security-ltpa2-core#4]
Hi @sephiroth-j 

any chance, you can provide your repo via https or upload the artifact to maven central or some other service? That be great.

Thanks!

**Comment by sephiroth-j** [comment]
Currently, only [the GitHub Packages repository](https://github.com/sephiroth-j/spring-security-ltpa2-core/packages/97997) is available with https. However, the next release is to be published on Sonatype OSS and thus Maven central.

**Comment by sephiroth-j** [comment]
HTTPS is now enabled for my own repository.
